### ISSUE TITLE
Usage of tokens in multiple places

### ISSUE THREAD

**Issue by tdankert** [iocchi/PetriNetPlans#21]
For generation of the plans it seems that it is usually meant to be linear during execution. I was not able to find a syntax for multiple transitions from one place to more than one place.
What I would like to accomplish is to split movement and text-to-speech (as shown in the image). Is there a way to do this?

![parallel](https://user-images.githubusercontent.com/14090993/30918710-9c47e9ba-a39f-11e7-8f27-478e12e15bef.png)

**Comment by iocchi** [comment]
Parallel execution of portions of a PNP can be obtained with the fork/join constructs.
An example is given in this plan
https://github.com/iocchi/PetriNetPlans/blob/master/PNPros/ROS_bridge/pnp_ros/plans/MultiRobot.png

Currenty, thePNPgen library does not include specifications and generation of plans with such a feature, but you can do it manually with the Jarp grapgical editor.
