### ISSUE TITLE
Class functions in register_action()

### ISSUE THREAD

**Issue by Tastalian** [iocchi/PetriNetPlans#4]
Hi,

In ROS, it is possible to subscribe to a topic with a class function, e.g. from inside an object:

    sub = nh.subscribe("/my_topic", 10, &MyClass::callback, this);

Could it be possible to do the same within an ActionServer, e.g. from the constructor:

    register_action("init", &MyClass::exec_init, this);

That would enable OOP constructions, and avoid global variables in one's code...

**Comment by g-gemignani** [comment]
Hello,

I just tested out and this is already possible. Let us know if you have any problem with it.

**Comment by Tastalian** [comment]
Oops, sorry for the noise. Thank you for your answer.
